scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081', 'discovery-service:8761', 'config-service:8888', 'gateway-service:8087']