spring:
  application:
    name: gateway-service
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]