spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVICE:http://localhost:8888}
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/task_db
    username: root
    password: root
  sql:
    init:
      mode: always
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
