spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: "[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]"
  application:
    name: "config-service"
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]